### ISSUE TITLE
Consider disable Alt-<Number>?

### ISSUE THREAD

**Issue by xuzhao9** [nharward/web-ext-control-n-tabs#1]
Hello, thank you for the addon! It works like a charm and solves my problem.
However, I am just wondering is it possible to disable the old shortcut of Alt-<Number>?

**Comment by nharward** [comment]
I'm not sure if it's possible or not. I'm curious why you'd want to disable it though - wouldn't it be more useful to map alt-? to something else?

**Comment by xuzhao9** [comment]
Just sometimes I will hit Alt-<number> by accident which I don't mean to.
I think probably you are right - and I think it is wiser to raise the problem of remapping after Mozilla fixes their inadequate WebAssembly shortcut API (See https://bugzilla.mozilla.org/show_bug.cgi?id=1215061).
Thanks all the same!
