### ISSUE TITLE
inconsistent "jump to last tab" behavior

### ISSUE THREAD

**Issue by mmao** [nharward/web-ext-control-n-tabs#2]
Per the Firefox docs: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs

Alt + 9 jumps to the last tab, but with Ctrl addon, Ctrl + 9 doesn't mirror that behavior.

**Comment by nharward** [comment]
Closing, fix is published and available for update.
